### ISSUE TITLE
Process for development & testing is undocumented

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/thrifty-builder#3]
The process for setting up a development environment and running thrifty-builder tests is undocumented.

**Comment by jrandall** [comment]
I think the problem I am currently having trying to figure this out is that thrifty-builder requires a relatively new docker daemon. Running against docker v1.8.3 results in tests that end with:
```
docker.errors.APIError: 400 Client Error: Bad Request ("b'client is newer than server (client API version: 1.35, server API version: 1.20)'")

----------------------------------------------------------------------
Ran 65 tests in 0.467s

FAILED (errors=53)
Test failed: <unittest.runner.TextTestResult run=65 errors=53 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=65 errors=53 failures=0>
```

**Comment by colin-nolan** [comment]
- Added section on development to README. 
- Notes minimum Docker version requirement in the README (v1.8.3 is 2.5 years out of date). The current error message should make the problem clear enough.
